apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-critical-alert
  namespace: monitoring-stack
  labels:
    release: k8s
spec:
  groups:
    - name: trivy-alert-group
      rules:
        - alert: CriticalVulnerabilityDetected
          expr: trivy_vulnerability_id{fixed_version!="",container_name="node-server-app-container",severity!="Unknown"} > 0
          for: 3m
          labels:
            severity: warning
        - alert: RootPrivellegeDetected
          expr: trivy_configaudits_info{exported_namespace="node-server-app",config_audit_description=~".*(privileges).*",config_audit_title=~".*(privileges).*",config_audit_success="false"} > 0
          for: 3m
          labels:
            deployment: node-server-app-vuln
            namespace: node-server-app
            severity: warning
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: update-request-alert
  namespace: monitoring-stack
  labels:
      release: k8s
spec:
  groups:
    - name: update-group
      rules:
        - alert: ContainerImageIsOutOfDate
          expr:  changes(kube_pod_container_info{container="node-server-app-container", namespace="node-server-app"}[5m]) == 0
          labels:
          annotations:
            summary: "Image auto-patch check"
            description: "Container image {{$labels.image_name}} requires an update"

          