apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-critical-alert
  namespace: prometheus-bundle
  labels:
    role: alert-rule
spec:
  groups:
    - name: trivy-alert-group
      rules:
        - alert: CriticalVulnerabilityDetected
          expr: trivy_vulnerability_id{container_name="node-server-app-container",severity="Critical"}>0
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "Critical vulnerability"
            description: "Trivy detect critical vulnerability in you resources"