apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-patcher
spec:
  schedule: "0 2 * * *"  # runs once daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: image-updater
            image: your-custom-image:latest
            env:
            - name: DEPLOYMENT_NAME
              value: "node-server-app-vuln"
            - name: NAMESPACE
              value: "node-server-app"
            - name: CONTAINER_NAME
              value: "node-server-app-container"
            - name: DOCKER_USERNAME
              value: "andrejp02"
            - name: DOCKER_REPO
              value: "prometheus_server"
          restartPolicy: OnFailure