apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-server-monitor
  namespace: node-server-app
  labels:
    app: node-server-monitor
    role: service-monitor
spec:
  selector:
    matchLabels:
      app: node-server
  endpoints:
    - port: web
      interval: 15s
      path: /metrics