apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  namespace: node-server-app
  labels:
    app: node-server
spec:
  selector:
    app: node-server
  ports:
    - name: web
      port: 4000
      targetPort: 4000