apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: auto-patch-namespace
  labels:
    app: postgres-service
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-deployment