apiVersion: v1
kind: Service
metadata:
  name: trivy-service
  namespace: container-scanner
  labels:
    name: trivy-metrics-service
spec:
  selector:
    name: trivy-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP

