apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-patch-service-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: automation-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: auto-patch-namespace
roleRef:
  kind: ClusterRole
  name: auto-patch-service-role
  apiGroup: rbac.authorization.k8s.io

