apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: automation-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: auto-update-deployment-namespace
- kind: ServiceAccount
  name: default
  namespace: auto-patch-namespace
roleRef:
  kind: ClusterRole
  name: automation-webhook-role
  apiGroup: rbac.authorization.k8s.io